@startuml Manage Booking (UPDATE)

header Hotel Booking Sequence Diagram
footer Page %page% of %lastpage%
title "Manage Booking (UPDATE)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:bookings" as routerBookings
participant "<<middleware>>\n:auth" as middleware
participant "<<controllers>>\n:bookings" as controllersBookings
participant "<<model>>\n:Booking" as modelBooking
database "<<MongoDB>>\n:bookings" as BookingsDatabase

client->server ++:req.put('/api/v1/bookings/:id')
server->routerBookings ++:app.use('/api/v1/bookings/:id',bookings)



routerBookings -> middleware ++: protect(),authorize('admin','user')

alt token not match/is null
    client <- middleware : not Authorize to access
end

middleware -> controllersBookings ++:updateBooking()

alt not own/not admin
    client <- controllersBookings :not authorized to update
end

controllersBookings->modelBooking ++:findByIdAndUpdate(req.params.id,req.body)

modelBooking ->BookingsDatabase ++: BookingSchema

BookingsDatabase --> modelBooking --: booking
controllersBookings <-- modelBooking --:booking
controllersBookings->client --:response

@enduml